### ISSUE TITLE
Stopped working for Google Images

### ISSUE THREAD

**Issue by vessto** [downthemall/anticontainer#102]
No files selected when dta anticontainer checked in Google image search. Till few days it still worked flawlessly selecting 100 per Google Images tab and I used it a lot to get what I needed. Now it selects nothing when checked.

![screenshot_284](https://cloud.githubusercontent.com/assets/14319978/9918143/db95d1d8-5ccd-11e5-80c4-81df233bcbe7.png)

**Comment by marianocarrazana** [comment]
Probably this will work better:
{
	"type": "redirector",
	"ns": "downthemall.net",
	"prefix": "google images",
	"match": "^https?://(?:[\\w\\d]+\\.)?google\\.[\\w\\.]+/imgres\\?",
	"pattern": "^.*imgurl=(.+?)(?:&.*)?$",
	"replacement": "$1",
	"omitReferrer": true,
	"decode": true
}
