### ISSUE TITLE
TypeError: s.getUsableFileName is not a function

### ISSUE THREAD

**Issue by poke** [downthemall/anticontainer#111]
Running AC on the fixed 2.x DTA, I get `TypeError: s.getUsableFileName is not a function` in the browser console. I added an explicit `log(LOG_ERROR)` inside the [function](https://github.com/downthemall/anticontainer/blob/2ae2912/content/manager.js#L32) to get an auxiliary stack trace for the call.

Auxiliary stack trace for a redirector plugin:

        >Source Frame (stack) :: chrome://dtaac/content/manager.js :: window.log :: line: 23
        >JS frame :: chrome://dtaac/content/manager.js :: Utils.getUsableFileName :: line 32
        >JS frame :: chrome://dtaac/content/manager.js :: acR_setURL :: line 250
        >JS frame :: chrome://dtaac/content/manager.js :: acFactory/this.obj.prototype.process :: line 710
        >JS frame :: chrome://dtaac/content/manager.js :: acR_run :: line 119
        >JS frame :: chrome://dtaac/content/manager.js :: acQ_resumeDownload :: line 826
        >JS frame :: chrome://dta/content/dta/manager/manager.js :: D_run :: line 916
    manager.js:23

Proper error thrown by DTA directly afterwards:

    ac::QueueItem::resumeDownload   Error: TypeError: s.getUsableFileName is not a function
        >Source Frame (error) :: chrome://dtaac/content/manager.js :: TypeError :: line: 32
        >JS frame :: chrome://dtaac/content/manager.js :: acQ_resumeDownload :: line 830
        >JS frame :: chrome://dta/content/dta/manager/manager.js :: D_run :: line 916
        >JS frame :: chrome://dta/content/dta/manager/manager.js :: D_startNext :: line 878
        >JS frame :: chrome://dta/content/dta/manager/manager.js :: D_checkDownloads :: line 839
        >JS frame :: resource://dta/support/timers.jsm :: TimerData.prototype.execute :: line 76
        >JS frame :: resource://dta/support/timers.jsm :: TimerData.prototype.observe :: line 72
    manager.js:32

Auxiliary stack trace for a sandbox plugin:

        >Source Frame (stack) :: chrome://dtaac/content/manager.js :: window.log :: line: 23
        >JS frame :: chrome://dtaac/content/manager.js :: Utils.getUsableFileName :: line 32
        >JS frame :: chrome://dtaac/content/manager.js :: acR_setURL :: line 250
        >JS frame :: chrome://dtaac/content/manager.js :: _setURL :: line 591
        >JS frame :: chrome://dtaac/content/sandboxscripts.js :: setURL :: line 11
        >JS frame :: imgur.com (galler redirect)-process :: <TOP_LEVEL> :: line 6
        >JS frame :: chrome://dtaac/content/sandboxscripts.js :: makeRequest/_r.onload :: line 79
    TypeError: s.getUsableFileName is not a function

**Comment by nmaier** [comment]
Well, I hope this fixed it, can you verify @poke ?

**Comment by poke** [comment]
Yup, working fine now. Seems we’re stable again.
