### ISSUE TITLE
Update various broken plugins

### ISSUE THREAD

**Issue by poke** [downthemall/anticontainer#114]
Tracking the update process of various plugins that are known to be broken:
- [x] Facebook (Photos, Videos)
- [x] <s>Facebook albums</s>
- [ ] Picasa Web Gallery
- [ ] Coppermine

If you know other plugins that don’t work but are not included on this list, please leave a comment below so I can add it.

**Comment by equate923** [comment]
Hi Poke, been using Anti-c for some time... may thanks for your efforts! I've also been using your unofficial ebay plugin for awhile now: https://bugs.downthemall.net/ticket/1388   However, it stopped working recently. Could I ask you to take a look at it? 

If you'd rather I make a new ticket for this issue please advise.

Thanks!

**Comment by poke** [comment]
@equate923 Wow, I don’t even remember that! Time surely flies! Yes, please create a separate issue for that, and I’ll see if we maybe can get a full plugin added to AC this time.

**Comment by equate923** [comment]
@poke  It sure does! I've been using anti-c since the very beginning... great software.

Just put up the new ticket: https://github.com/downthemall/anticontainer/issues/116
